# caterchef-backend/.github/workflows/backend-ci.yml
name: CaterChef Backend CI (Integración Continua)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test-backend:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar código del repositorio
      uses: actions/checkout@v4

    - name: Configurar entorno de Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Cachear dependencias de Pip
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Instalar dependencias del proyecto
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # --- MODIFICADO: Inyectamos una variable de entorno mock para la inicialización del contenedor de pruebas ---
    - name: Ejecutar Suite de Pruebas Unitarias (Pytest)
      env:
        DATABASE_URL: sqlite:///:memory:
        SECRET_KEY: clave_temporal_de_pruebas_para_github_actions
        ALGORITHM: HS256
      run: |
        python -m pytest -v