name: Backend CI

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      DATABASE_URL: "sqlite:///./test.db"
      SECRET_KEY: "clave_test_tfg_2026"
      ALGORITHM: "HS256"

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Instalar dependencias
        run: pip install -r requirements.txt
      - name: Ejecutar Tests
        run: python -m pytest -v
